name: deep_linking
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  beamer: ^1.5.4
  cupertino_icons: ^1.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get: ^4.6.5
  get_it: ^7.6.0
  go_router: ^8.0.5
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
