name: deep_linking
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get: ^4.6.5
  go_router: ^6.5.7
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
